### ISSUE TITLE
TOML 规范兼容问题

### ISSUE THREAD

**Issue by uioz** [uioz/webpack-tomlenv-plugin#2]
# 说明

规范地址:
> https://toml.io/en/v1.0.0

目前存在的最大问题是 `toml` 支持对 key 和 table 进行分组:
```toml
name = "Orange"
physical.color = "orange"
physical.shape = "round"
site."google.com" = true
```

结果:
```json
{
  "name": "Orange",
  "physical": {
    "color": "orange",
    "shape": "round"
  },
  "site": {
    "google.com": true
  }
}
```

而 `webpack.definePlugin` 本质是将解析到的 `key` 替换为对应的 value, 只会解析对象的第一层.

如果我们将转为 JSON 的结构进行遍历, 将无法解决值为键值对的问题, 因为无法进行区分对象到底是否值还是用作键.
```toml
physical.color = {type = 'a'}
physical.shape = {mode = 'b'}
```

目前暂定的是不对 `toml` 的点号连接符语法做支持, 用户可以这样编写, 但是得到的结果是错误的.
